version: '3.8'

services:
  blog-app:
    build: .
    container_name: blog-spring-boot
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx512m -Xms256m
    volumes:
      - blog_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Opcional: Agregar una base de datos PostgreSQL para producción
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: blog-postgres
  #   environment:
  #     POSTGRES_DB: blogdb
  #     POSTGRES_USER: bloguser
  #     POSTGRES_PASSWORD: blogpass
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

volumes:
  blog_logs:
  # postgres_data:

networks:
  default:
    name: blog-network
